on:
  push:
    branches: [master]
  pull_request:
name: Build Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: qdigidoc.flatpak
        manifest-path: ee.ria.qdigidoc4.yml
        cache-key: flatpak-builder-${{ github.sha }}
