on: workflow_dispatch
name: Build and release
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: qdigidoc.flatpak
        manifest-path: ee.ria.qdigidoc4.yml
        cache-key: flatpak-builder-${{ github.sha }}
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: qdigidoc-x86_64
          path: qidigidoc.flatpak
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          body: |
            ```
            flatpak install qdigidoc.flatpak
            ```
          files: qidigidoc.flatpak

